export type Micro =
  | 'potassium'
  | 'magnesium'
  | 'calcium'
  | 'iron'
  | 'zinc'
  | 'folate'
  | 'vitamin_a'
  | 'vitamin_c'
  | 'vitamin_d'
  | 'vitamin_e'
  | 'b12'
  | 'omega3'
  | 'selenium'
  | 'iodine'
  | 'sodium'
  | 'vitamin_k'
  | 'vitamin_b6'
  | 'manganese'
  | 'copper'
  | 'phosphorus';

export type MicroDetailKey = Micro;

export interface FoodNutrition {
  kcal: number;
  protein: number; // g
  carbs: number;   // g
  fats: number;    // g
  fiber: number;   // g
  // Microelementi per 100g (valori indicativi)
  micronutrients?: {
    potassium?: number;       // mg
    magnesium?: number;       // mg
    calcium?: number;         // mg
    iron?: number;            // mg
    zinc?: number;            // mg
    folate?: number;          // µg
    vitamin_a?: number;       // µg RAE
    vitamin_c?: number;       // mg
    vitamin_d?: number;       // µg
    vitamin_e?: number;       // mg
    b12?: number;             // µg
    omega3?: number;          // mg
    selenium?: number;        // µg
    iodine?: number;          // µg
    sodium?: number;          // mg
    vitamin_k?: number;       // µg
    vitamin_b6?: number;      // mg
    manganese?: number;       // mg
    copper?: number;          // mg
    phosphorus?: number;      // mg
  };
}

export interface FoodItem {
  id: string;
  name: string;
  category: 'Carboidrati/Cereali' | 'Proteine/Formaggi' | 'Verdura' | 'Frutta' | 'Condimenti/Altro';
  fodmapLevel: 'low' | 'high';
  triggerGroup?: 'Fruttani' | 'Lattosio' | 'Fruttosio' | 'Galattani' | 'Polioli';
  alternative?: string;
  /** Mesi (1-12) di disponibilità tipica del prodotto fresco in ambito mediterraneo. Omesso = disponibile tutto l'anno (conserve, essiccati, allevamento, importazione continua). */
  months?: number[];
  /** Valori nutrizionali indicativi per 100g di parte edibile */
  nutrition: FoodNutrition;
  /** Oligoelementi/micronutrienti di cui l'alimento è fonte rilevante */
  micros?: Micro[];
  /** Dettaglio quantitativo dei micronutrienti per 100g */
  microDetails?: Partial<Record<MicroDetailKey, number>>;
}

export const FOODS_DATABASE: FoodItem[] = [
  // CEREALI E CARBOIDRATI
  { id: '1', name: 'Pane di Frumento / Pasta comune', category: 'Carboidrati/Cereali', fodmapLevel: 'high', triggerGroup: 'Fruttani', alternative: 'Riso, avena, quinoa o prodotti certificati Gluten-Free', nutrition: { kcal: 290, protein: 9, carbs: 55, fats: 2, fiber: 3, micronutrients: { iron: 2.5, folate: 35, sodium: 400, phosphorus: 120 } }, micros: ['iron', 'folate'], microDetails: { iron: 2.5, folate: 35, sodium: 400, phosphorus: 120 } },
  { id: '2', name: 'Riso Bianco e Integrale', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 360, protein: 6.7, carbs: 80, fats: 0.4, fiber: 1.3, micronutrients: { magnesium: 25, sodium: 5, phosphorus: 95 } }, micros: ['magnesium'], microDetails: { magnesium: 25, sodium: 5, phosphorus: 95 } },
  { id: '3', name: 'Avena in fiocchi', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 389, protein: 16.9, carbs: 66, fats: 6.9, fiber: 10.6, micronutrients: { magnesium: 177, iron: 4.7, zinc: 4, sodium: 2, phosphorus: 523, copper: 0.6, manganese: 4 } }, micros: ['magnesium', 'iron', 'zinc'], microDetails: { magnesium: 177, iron: 4.7, zinc: 4, sodium: 2, phosphorus: 523, copper: 0.6, manganese: 4 } },
  { id: '15', name: 'Quinoa', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 368, protein: 14.1, carbs: 64, fats: 6.1, fiber: 7, micronutrients: { magnesium: 197, iron: 2.8, folate: 184, sodium: 5, phosphorus: 457, zinc: 3.1, manganese: 2 } }, micros: ['magnesium', 'iron', 'folate'], microDetails: { magnesium: 197, iron: 2.8, folate: 184, sodium: 5, phosphorus: 457, zinc: 3.1, manganese: 2 } },
  { id: '16', name: 'Mais / Polenta', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 365, protein: 9.4, carbs: 74, fats: 4.7, fiber: 7.3, micronutrients: { magnesium: 37, sodium: 1, phosphorus: 272, vitamin_b6: 0.6 } }, micros: ['magnesium'], microDetails: { magnesium: 37, sodium: 1, phosphorus: 272, vitamin_b6: 0.6 } },
  { id: '17', name: 'Grano Saraceno', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 343, protein: 13.3, carbs: 71.5, fats: 3.4, fiber: 10, micronutrients: { magnesium: 231, iron: 2.2, sodium: 1, phosphorus: 347, copper: 1.1, manganese: 1.3 } }, micros: ['magnesium', 'iron'], microDetails: { magnesium: 231, iron: 2.2, sodium: 1, phosphorus: 347, copper: 1.1, manganese: 1.3 } },
  { id: '18', name: 'Pane e Pasta Gluten-Free certificati', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 260, protein: 5, carbs: 48, fats: 5, fiber: 4, micronutrients: { iron: 1.5, sodium: 300, phosphorus: 90, folate: 15 } }, micros: ['iron'], microDetails: { iron: 1.5, sodium: 300, phosphorus: 90, folate: 15 } },
  { id: '45', name: 'Tagliatelle di Shirataki (konjac)', category: 'Carboidrati/Cereali', fodmapLevel: 'low', nutrition: { kcal: 10, protein: 0.2, carbs: 0.2, fats: 0, fiber: 2.7, micronutrients: { calcium: 20, sodium: 10 } }, micros: ['calcium'], microDetails: { calcium: 20, sodium: 10 } },
  { id: '46', name: 'Farro perlato', category: 'Carboidrati/Cereali', fodmapLevel: 'high', triggerGroup: 'Fruttani', alternative: 'Orzo decorticato, avena o riso integrale', nutrition: { kcal: 340, protein: 14, carbs: 70, fats: 2, fiber: 8, micronutrients: { magnesium: 115, iron: 3.6, zinc: 3.2, phosphorus: 380, sodium: 5 } }, micros: ['magnesium', 'iron', 'zinc'], microDetails: { magnesium: 115, iron: 3.6, zinc: 3.2, phosphorus: 380, sodium: 5 } },

  // VERDURA
  { id: '4', name: 'Aglio e Cipolla', category: 'Verdura', fodmapLevel: 'high', triggerGroup: 'Fruttani', alternative: 'Erba cipollina o olio infuso all\'aglio (i FODMAP non sono solubili nei grassi)', months: [6, 7, 8, 9, 10], nutrition: { kcal: 45, protein: 1.4, carbs: 10, fats: 0.1, fiber: 1.7, micronutrients: { vitamin_c: 31, sodium: 12, vitamin_b6: 0.3, manganese: 0.2 } }, micros: ['vitamin_c'], microDetails: { vitamin_c: 31, sodium: 12, vitamin_b6: 0.3, manganese: 0.2 } },
  { id: '5', name: 'Zucchine', category: 'Verdura', fodmapLevel: 'low', months: [5, 6, 7, 8, 9], nutrition: { kcal: 17, protein: 1.2, carbs: 3.1, fats: 0.3, fiber: 1, micronutrients: { potassium: 261, folate: 24, sodium: 8, vitamin_c: 18 } }, micros: ['potassium', 'folate'], microDetails: { potassium: 261, folate: 24, sodium: 8, vitamin_c: 18 } },
  { id: '6', name: 'Carote', category: 'Verdura', fodmapLevel: 'low', nutrition: { kcal: 41, protein: 0.9, carbs: 9.6, fats: 0.2, fiber: 2.8, micronutrients: { vitamin_a: 835, potassium: 320, sodium: 69, vitamin_k: 13, vitamin_b6: 0.2 } }, micros: ['vitamin_a', 'potassium'], microDetails: { vitamin_a: 835, potassium: 320, sodium: 69, vitamin_k: 13, vitamin_b6: 0.2 } },
  { id: '7', name: 'Carciofi e Scalogno', category: 'Verdura', fodmapLevel: 'high', triggerGroup: 'Fruttani', alternative: 'Finocchi (porzione moderata) o ravanelli', months: [1, 2, 3, 4, 5, 10, 11, 12], nutrition: { kcal: 47, protein: 3.3, carbs: 10.5, fats: 0.2, fiber: 5.4, micronutrients: { folate: 89, magnesium: 60, potassium: 370, sodium: 94, vitamin_c: 12, vitamin_k: 14 } }, micros: ['folate', 'magnesium', 'potassium'], microDetails: { folate: 89, magnesium: 60, potassium: 370, sodium: 94, vitamin_c: 12, vitamin_k: 14 } },
  { id: '19', name: 'Spinaci freschi', category: 'Verdura', fodmapLevel: 'low', months: [1, 2, 3, 4, 5, 9, 10, 11, 12], nutrition: { kcal: 23, protein: 2.9, carbs: 3.6, fats: 0.4, fiber: 2.2, micronutrients: { iron: 2.7, folate: 194, magnesium: 79, vitamin_a: 469, sodium: 79, vitamin_k: 483, calcium: 99, vitamin_c: 28 } }, micros: ['iron', 'folate', 'magnesium', 'vitamin_a'], microDetails: { iron: 2.7, folate: 194, magnesium: 79, vitamin_a: 469, sodium: 79, vitamin_k: 483, calcium: 99, vitamin_c: 28 } },
  { id: '20', name: 'Finocchio', category: 'Verdura', fodmapLevel: 'low', months: [1, 2, 3, 4, 9, 10, 11, 12], nutrition: { kcal: 31, protein: 1.2, carbs: 7.3, fats: 0.2, fiber: 3.1, micronutrients: { potassium: 414, vitamin_c: 12, sodium: 45, folate: 27, calcium: 49 } }, micros: ['potassium', 'vitamin_c'], microDetails: { potassium: 414, vitamin_c: 12, sodium: 45, folate: 27, calcium: 49 } },
  { id: '21', name: 'Peperoni', category: 'Verdura', fodmapLevel: 'low', months: [6, 7, 8, 9, 10], nutrition: { kcal: 26, protein: 1, carbs: 6, fats: 0.3, fiber: 2.1, micronutrients: { vitamin_c: 128, vitamin_a: 313, sodium: 4, vitamin_b6: 0.3, folate: 46 } }, micros: ['vitamin_c', 'vitamin_a'], microDetails: { vitamin_c: 128, vitamin_a: 313, sodium: 4, vitamin_b6: 0.3, folate: 46 } },
  { id: '22', name: 'Pomodori', category: 'Verdura', fodmapLevel: 'low', months: [6, 7, 8, 9], nutrition: { kcal: 18, protein: 0.9, carbs: 3.9, fats: 0.2, fiber: 1.2, micronutrients: { potassium: 237, vitamin_c: 14, sodium: 5, vitamin_k: 8, vitamin_a: 42 } }, micros: ['potassium', 'vitamin_c'], microDetails: { potassium: 237, vitamin_c: 14, sodium: 5, vitamin_k: 8, vitamin_a: 42 } },
  { id: '23', name: 'Cavolfiore', category: 'Verdura', fodmapLevel: 'high', triggerGroup: 'Polioli', alternative: 'Broccoli (cimette) o verza in porzioni controllate', months: [1, 2, 3, 4, 10, 11, 12], nutrition: { kcal: 25, protein: 1.9, carbs: 5, fats: 0.3, fiber: 2, micronutrients: { vitamin_c: 48, folate: 57, sodium: 15, vitamin_k: 15, vitamin_b6: 0.2 } }, micros: ['vitamin_c', 'folate'], microDetails: { vitamin_c: 48, folate: 57, sodium: 15, vitamin_k: 15, vitamin_b6: 0.2 } },
  { id: '24', name: 'Patate', category: 'Verdura', fodmapLevel: 'low', months: [8, 9, 10], nutrition: { kcal: 77, protein: 2, carbs: 17, fats: 0.1, fiber: 2.2, micronutrients: { potassium: 425, vitamin_c: 20, sodium: 6, vitamin_b6: 0.3, magnesium: 23 } }, micros: ['potassium', 'vitamin_c'], microDetails: { potassium: 425, vitamin_c: 20, sodium: 6, vitamin_b6: 0.3, magnesium: 23 } },
  { id: '25', name: 'Zucca (butternut)', category: 'Verdura', fodmapLevel: 'low', months: [1, 9, 10, 11, 12], nutrition: { kcal: 45, protein: 1, carbs: 11.7, fats: 0.1, fiber: 2, micronutrients: { vitamin_a: 532, potassium: 352, sodium: 4, folate: 27, vitamin_c: 21 } }, micros: ['vitamin_a', 'potassium'], microDetails: { vitamin_a: 532, potassium: 352, sodium: 4, folate: 27, vitamin_c: 21 } },
  { id: '26', name: 'Melanzane', category: 'Verdura', fodmapLevel: 'low', months: [6, 7, 8, 9], nutrition: { kcal: 25, protein: 1, carbs: 5.9, fats: 0.2, fiber: 3, micronutrients: { potassium: 229, folate: 22, sodium: 2, manganese: 0.2, copper: 0.1 } }, micros: ['potassium', 'folate'], microDetails: { potassium: 229, folate: 22, sodium: 2, manganese: 0.2, copper: 0.1 } },
  { id: '47', name: 'Broccoli (cimette)', category: 'Verdura', fodmapLevel: 'low', months: [1, 2, 3, 4, 10, 11, 12], nutrition: { kcal: 34, protein: 2.8, carbs: 7, fats: 0.4, fiber: 2.6, micronutrients: { vitamin_c: 89, vitamin_k: 102, folate: 63, potassium: 316, sodium: 33, vitamin_a: 31 } }, micros: ['vitamin_c', 'vitamin_k', 'folate', 'potassium'], microDetails: { vitamin_c: 89, vitamin_k: 102, folate: 63, potassium: 316, sodium: 33, vitamin_a: 31 } },
  { id: '48', name: 'Asparagi', category: 'Verdura', fodmapLevel: 'high', triggerGroup: 'Fruttani', alternative: 'Zucchine, fiori di zucca o verza', months: [3, 4, 5], nutrition: { kcal: 20, protein: 2.2, carbs: 3.9, fats: 0.1, fiber: 2.1, micronutrients: { folate: 52, vitamin_k: 42, vitamin_a: 38, potassium: 202, sodium: 2 } }, micros: ['folate', 'vitamin_k', 'vitamin_a'], microDetails: { folate: 52, vitamin_k: 42, vitamin_a: 38, potassium: 202, sodium: 2 } },
  { id: '49', name: 'Cetrioli', category: 'Verdura', fodmapLevel: 'low', months: [5, 6, 7, 8, 9], nutrition: { kcal: 15, protein: 0.7, carbs: 3.6, fats: 0.1, fiber: 0.5, micronutrients: { vitamin_k: 16, potassium: 147, sodium: 2, vitamin_c: 3 } }, micros: ['vitamin_k', 'potassium'], microDetails: { vitamin_k: 16, potassium: 147, sodium: 2, vitamin_c: 3 } },
  { id: '50', name: 'Rucola', category: 'Verdura', fodmapLevel: 'low', months: [3, 4, 5, 9, 10], nutrition: { kcal: 25, protein: 2.6, carbs: 3.7, fats: 0.7, fiber: 1.6, micronutrients: { vitamin_k: 109, vitamin_a: 237, folate: 97, calcium: 160, potassium: 369, sodium: 27 } }, micros: ['vitamin_k', 'vitamin_a', 'folate', 'calcium'], microDetails: { vitamin_k: 109, vitamin_a: 237, folate: 97, calcium: 160, potassium: 369, sodium: 27 } },
  { id: '51', name: 'Barbabietola rossa cotta', category: 'Verdura', fodmapLevel: 'low', months: [1, 2, 3, 10, 11, 12], nutrition: { kcal: 44, protein: 1.7, carbs: 10, fats: 0.2, fiber: 2, micronutrients: { folate: 80, manganese: 0.3, potassium: 305, sodium: 77, iron: 0.8 } }, micros: ['folate', 'manganese', 'potassium'], microDetails: { folate: 80, manganese: 0.3, potassium: 305, sodium: 77, iron: 0.8 } },

  // FRUTTA
  { id: '8', name: 'Mele e Pere', category: 'Frutta', fodmapLevel: 'high', triggerGroup: 'Fruttosio', alternative: 'Fragole, mirtilli, arance o kiwi', months: [1, 2, 8, 9, 10, 11, 12], nutrition: { kcal: 52, protein: 0.3, carbs: 14, fats: 0.2, fiber: 2.4, micronutrients: { vitamin_c: 4.6, potassium: 107, sodium: 1, vitamin_k: 2 } }, micros: ['vitamin_c', 'potassium'], microDetails: { vitamin_c: 4.6, potassium: 107, sodium: 1, vitamin_k: 2 } },
  { id: '9', name: 'Fragole e Mirtilli', category: 'Frutta', fodmapLevel: 'low', months: [4, 5, 6, 7, 8, 9], nutrition: { kcal: 40, protein: 0.7, carbs: 9, fats: 0.3, fiber: 2, micronutrients: { vitamin_c: 59, folate: 24, sodium: 1, manganese: 0.4, vitamin_k: 2 } }, micros: ['vitamin_c', 'folate'], microDetails: { vitamin_c: 59, folate: 24, sodium: 1, manganese: 0.4, vitamin_k: 2 } },
  { id: '10', name: 'Anguria', category: 'Frutta', fodmapLevel: 'high', triggerGroup: 'Polioli', alternative: 'Melone cantalupo (in porzioni controllate)', months: [6, 7, 8, 9], nutrition: { kcal: 30, protein: 0.6, carbs: 7.6, fats: 0.2, fiber: 0.4, micronutrients: { vitamin_a: 28, vitamin_c: 8.1, sodium: 1, potassium: 112 } }, micros: ['vitamin_a', 'vitamin_c'], microDetails: { vitamin_a: 28, vitamin_c: 8.1, sodium: 1, potassium: 112 } },
  { id: '27', name: 'Arance e Mandarini', category: 'Frutta', fodmapLevel: 'low', months: [1, 2, 3, 4, 11, 12], nutrition: { kcal: 47, protein: 0.9, carbs: 11.8, fats: 0.1, fiber: 2.4, micronutrients: { vitamin_c: 53, folate: 40, sodium: 0, potassium: 181, calcium: 40 } }, micros: ['vitamin_c', 'folate'], microDetails: { vitamin_c: 53, folate: 40, sodium: 0, potassium: 181, calcium: 40 } },
  { id: '28', name: 'Kiwi', category: 'Frutta', fodmapLevel: 'low', months: [1, 2, 3, 11, 12], nutrition: { kcal: 61, protein: 1.1, carbs: 14.7, fats: 0.5, fiber: 3, micronutrients: { vitamin_c: 93, sodium: 3, potassium: 312, vitamin_k: 40, vitamin_e: 1.5, folate: 25 } }, micros: ['vitamin_c'], microDetails: { vitamin_c: 93, sodium: 3, potassium: 312, vitamin_k: 40, vitamin_e: 1.5, folate: 25 } },
  { id: '29', name: 'Banana (soda, non matura)', category: 'Frutta', fodmapLevel: 'low', nutrition: { kcal: 89, protein: 1.1, carbs: 22.8, fats: 0.3, fiber: 2.6, micronutrients: { potassium: 358, magnesium: 27, sodium: 1, vitamin_b6: 0.4, manganese: 0.3, vitamin_c: 9 } }, micros: ['potassium', 'magnesium'], microDetails: { potassium: 358, magnesium: 27, sodium: 1, vitamin_b6: 0.4, manganese: 0.3, vitamin_c: 9 } },
  { id: '30', name: 'Melone cantalupo', category: 'Frutta', fodmapLevel: 'low', months: [6, 7, 8, 9], nutrition: { kcal: 34, protein: 0.8, carbs: 8.2, fats: 0.2, fiber: 0.9, micronutrients: { vitamin_a: 169, potassium: 267, sodium: 16, folate: 21, vitamin_c: 37 } }, micros: ['vitamin_a', 'potassium'], microDetails: { vitamin_a: 169, potassium: 267, sodium: 16, folate: 21, vitamin_c: 37 } },
  { id: '31', name: 'Ananas', category: 'Frutta', fodmapLevel: 'low', nutrition: { kcal: 50, protein: 0.5, carbs: 13.1, fats: 0.1, fiber: 1.4, micronutrients: { vitamin_c: 48, sodium: 1, manganese: 0.9, vitamin_b6: 0.1, folate: 18 } }, micros: ['vitamin_c'], microDetails: { vitamin_c: 48, sodium: 1, manganese: 0.9, vitamin_b6: 0.1, folate: 18 } },
  { id: '32', name: 'Ciliegie', category: 'Frutta', fodmapLevel: 'high', triggerGroup: 'Polioli', alternative: 'Uva (porzione controllata) o fragole', months: [5, 6, 7], nutrition: { kcal: 63, protein: 1.1, carbs: 16, fats: 0.2, fiber: 2.1, micronutrients: { potassium: 222, vitamin_c: 7, sodium: 0, vitamin_a: 3, copper: 0.1 } }, micros: ['potassium', 'vitamin_c'], microDetails: { potassium: 222, vitamin_c: 7, sodium: 0, vitamin_a: 3, copper: 0.1 } },
  { id: '52', name: 'Papaia', category: 'Frutta', fodmapLevel: 'low', nutrition: { kcal: 43, protein: 0.5, carbs: 11, fats: 0.3, fiber: 1.7, micronutrients: { vitamin_c: 61, vitamin_a: 47, folate: 38, potassium: 182, vitamin_e: 0.3 } }, micros: ['vitamin_c', 'vitamin_a', 'folate', 'potassium'], microDetails: { vitamin_c: 61, vitamin_a: 47, folate: 38, potassium: 182, vitamin_e: 0.3 } },
  { id: '53', name: 'Lamponi', category: 'Frutta', fodmapLevel: 'low', months: [6, 7, 8, 9], nutrition: { kcal: 52, protein: 1.2, carbs: 12, fats: 0.7, fiber: 6.5, micronutrients: { vitamin_c: 26, manganese: 0.7, vitamin_k: 8, folate: 21, potassium: 151 } }, micros: ['vitamin_c', 'manganese', 'vitamin_k', 'folate'], microDetails: { vitamin_c: 26, manganese: 0.7, vitamin_k: 8, folate: 21, potassium: 151 } },
  { id: '54', name: 'Prugne secche (senza nocciolo)', category: 'Frutta', fodmapLevel: 'high', triggerGroup: 'Fruttosio', alternative: 'Fichi secchi piccola porzione o fragole', nutrition: { kcal: 240, protein: 2.2, carbs: 64, fats: 0.4, fiber: 7.1, micronutrients: { vitamin_k: 60, potassium: 732, vitamin_a: 39, iron: 0.9, sodium: 2 } }, micros: ['vitamin_k', 'potassium'], microDetails: { vitamin_k: 60, potassium: 732, vitamin_a: 39, iron: 0.9, sodium: 2 } },
  { id: '55', name: 'Uva (porzione controllata)', category: 'Frutta', fodmapLevel: 'low', months: [8, 9, 10], nutrition: { kcal: 69, protein: 0.7, carbs: 18, fats: 0.2, fiber: 0.9, micronutrients: { vitamin_k: 15, vitamin_c: 3, potassium: 191, vitamin_b6: 0.1, copper: 0.1 } }, micros: ['vitamin_k', 'potassium'], microDetails: { vitamin_k: 15, vitamin_c: 3, potassium: 191, vitamin_b6: 0.1, copper: 0.1 } },

  // LATTIOSI E PROTEINE
  { id: '11', name: 'Latte vaccino e Formaggi freschi', category: 'Proteine/Formaggi', fodmapLevel: 'high', triggerGroup: 'Lattosio', alternative: 'Latte senza lattosio o formaggi stagionati (Parmigiano Reggiano)', nutrition: { kcal: 61, protein: 3.2, carbs: 4.8, fats: 3.3, fiber: 0, micronutrients: { calcium: 120, vitamin_d: 1.2, b12: 0.4, sodium: 50, phosphorus: 95, iodine: 30 } }, micros: ['calcium', 'vitamin_d', 'b12'], microDetails: { calcium: 120, vitamin_d: 1.2, b12: 0.4, sodium: 50, phosphorus: 95, iodine: 30 } },
  { id: '12', name: 'Parmigiano Reggiano / Grana Padano', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 431, protein: 38, carbs: 4.1, fats: 29, fiber: 0, micronutrients: { calcium: 1184, zinc: 5.2, b12: 1.5, sodium: 1500, phosphorus: 760, vitamin_a: 56 } }, micros: ['calcium', 'zinc', 'b12'], microDetails: { calcium: 1184, zinc: 5.2, b12: 1.5, sodium: 1500, phosphorus: 760, vitamin_a: 56 } },
  { id: '13', name: 'Uova e Carne fresca', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 155, protein: 22, carbs: 0.5, fats: 7, fiber: 0, micronutrients: { b12: 1.1, zinc: 4.5, iron: 1.2, selenium: 24, sodium: 70, phosphorus: 180, vitamin_d: 1.0 } }, micros: ['b12', 'zinc', 'iron', 'selenium'], microDetails: { b12: 1.1, zinc: 4.5, iron: 1.2, selenium: 24, sodium: 70, phosphorus: 180, vitamin_d: 1.0 } },
  { id: '14', name: 'Legumi (Fagioli, Lenticchie comuni)', category: 'Proteine/Formaggi', fodmapLevel: 'high', triggerGroup: 'Galattani', alternative: 'Tofu sodo o lenticchie in scatola scolate e risciacquate molto bene', nutrition: { kcal: 116, protein: 9, carbs: 20, fats: 0.4, fiber: 7.9, micronutrients: { iron: 5.5, folate: 379, magnesium: 140, zinc: 2.5, sodium: 5, potassium: 350, phosphorus: 360, copper: 0.5, manganese: 1.0 } }, micros: ['iron', 'folate', 'magnesium', 'zinc'], microDetails: { iron: 5.5, folate: 379, magnesium: 140, zinc: 2.5, sodium: 5, potassium: 350, phosphorus: 360, copper: 0.5, manganese: 1.0 } },
  { id: '33', name: 'Petto di Pollo / Tacchino', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 135, protein: 27, carbs: 0, fats: 3, fiber: 0, micronutrients: { zinc: 2.5, b12: 0.3, selenium: 22, sodium: 60, phosphorus: 200, vitamin_b6: 0.6 } }, micros: ['zinc', 'b12', 'selenium'], microDetails: { zinc: 2.5, b12: 0.3, selenium: 22, sodium: 60, phosphorus: 200, vitamin_b6: 0.6 } },
  { id: '34', name: 'Pesce azzurro (Sarde, Sgombro)', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 208, protein: 25, carbs: 0, fats: 11.5, fiber: 0, micronutrients: { omega3: 1800, vitamin_d: 12, b12: 8.9, iodine: 45, selenium: 45, sodium: 90, phosphorus: 490 } }, micros: ['omega3', 'vitamin_d', 'b12', 'iodine', 'selenium'], microDetails: { omega3: 1800, vitamin_d: 12, b12: 8.9, iodine: 45, selenium: 45, sodium: 90, phosphorus: 490 } },
  { id: '35', name: 'Tofu sodo', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 76, protein: 8, carbs: 1.9, fats: 4.8, fiber: 0.3, micronutrients: { calcium: 530, magnesium: 60, sodium: 15, iron: 2.0, zinc: 1.0, phosphorus: 190 } }, micros: ['calcium', 'magnesium'], microDetails: { calcium: 530, magnesium: 60, sodium: 15, iron: 2.0, zinc: 1.0, phosphorus: 190 } },
  { id: '36', name: 'Yogurt greco senza lattosio', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 59, protein: 10, carbs: 3.6, fats: 0.4, fiber: 0, micronutrients: { calcium: 110, b12: 0.5, sodium: 70, phosphorus: 135, iodine: 25 } }, micros: ['calcium', 'b12'], microDetails: { calcium: 110, b12: 0.5, sodium: 70, phosphorus: 135, iodine: 25 } },
  { id: '56', name: 'Mozzarella di bufala', category: 'Proteine/Formaggi', fodmapLevel: 'high', triggerGroup: 'Lattosio', alternative: 'Mozzarella senza lattosio o formaggi stagionati', nutrition: { kcal: 288, protein: 19, carbs: 2, fats: 22, fiber: 0, micronutrients: { calcium: 500, b12: 0.6, sodium: 500, phosphorus: 350, vitamin_a: 100 } }, micros: ['calcium', 'b12'], microDetails: { calcium: 500, b12: 0.6, sodium: 500, phosphorus: 350, vitamin_a: 100 } },
  { id: '57', name: 'Tempeh', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 193, protein: 19, carbs: 9, fats: 11, fiber: 0, micronutrients: { iron: 2.7, magnesium: 81, phosphorus: 266, zinc: 1.1, copper: 0.6, manganese: 1.3, b12: 0.1, sodium: 9 } }, micros: ['iron', 'magnesium', 'phosphorus', 'zinc'], microDetails: { iron: 2.7, magnesium: 81, phosphorus: 266, zinc: 1.1, copper: 0.6, manganese: 1.3, b12: 0.1, sodium: 9 } },
  { id: '58', name: 'Manzo magro', category: 'Proteine/Formaggi', fodmapLevel: 'low', nutrition: { kcal: 250, protein: 26, carbs: 0, fats: 15, fiber: 0, micronutrients: { iron: 2.6, zinc: 4.8, b12: 2.6, selenium: 20, phosphorus: 200, vitamin_b6: 0.4, sodium: 60 } }, micros: ['iron', 'zinc', 'b12', 'selenium'], microDetails: { iron: 2.6, zinc: 4.8, b12: 2.6, selenium: 20, phosphorus: 200, vitamin_b6: 0.4, sodium: 60 } },

  // CONDIMENTI, GRASSI, BEVANDE E ALTRI
  { id: '37', name: 'Olio EVO', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 884, protein: 0, carbs: 0, fats: 100, fiber: 0, micronutrients: { vitamin_e: 14, sodium: 2, vitamin_k: 60 } }, micros: ['vitamin_e'], microDetails: { vitamin_e: 14, sodium: 2, vitamin_k: 60 } },
  { id: '38', name: 'Mandorle (max ~10)', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 579, protein: 21, carbs: 21.6, fats: 49.9, fiber: 12.5, micronutrients: { magnesium: 270, vitamin_e: 26, calcium: 269, sodium: 1, phosphorus: 481, copper: 1.0, manganese: 2.2, zinc: 3.1 } }, micros: ['magnesium', 'vitamin_e', 'calcium'], microDetails: { magnesium: 270, vitamin_e: 26, calcium: 269, sodium: 1, phosphorus: 481, copper: 1.0, manganese: 2.2, zinc: 3.1 } },
  { id: '39', name: 'Semi di Chia', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 486, protein: 16.5, carbs: 42.1, fats: 30.7, fiber: 34.4, micronutrients: { omega3: 17000, calcium: 631, magnesium: 335, sodium: 16, phosphorus: 860, zinc: 4.6, iron: 7.7 } }, micros: ['omega3', 'calcium', 'magnesium'], microDetails: { omega3: 17000, calcium: 631, magnesium: 335, sodium: 16, phosphorus: 860, zinc: 4.6, iron: 7.7 } },
  { id: '40', name: 'Semi di Zucca', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 559, protein: 30.2, carbs: 10.7, fats: 49, fiber: 6, micronutrients: { magnesium: 592, zinc: 7.6, iron: 8.8, sodium: 7, phosphorus: 1230, copper: 1.4, manganese: 4.5 } }, micros: ['magnesium', 'zinc', 'iron'], microDetails: { magnesium: 592, zinc: 7.6, iron: 8.8, sodium: 7, phosphorus: 1230, copper: 1.4, manganese: 4.5 } },
  { id: '41', name: 'Cioccolato fondente ≥70%', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 598, protein: 7.8, carbs: 45.9, fats: 42.6, fiber: 10.9, micronutrients: { magnesium: 228, iron: 11.9, zinc: 3.3, sodium: 20, phosphorus: 310, copper: 1.8, manganese: 1.9 } }, micros: ['magnesium', 'iron', 'zinc'], microDetails: { magnesium: 228, iron: 11.9, zinc: 3.3, sodium: 20, phosphorus: 310, copper: 1.8, manganese: 1.9 } },
  { id: '42', name: 'Miele', category: 'Condimenti/Altro', fodmapLevel: 'high', triggerGroup: 'Fruttosio', alternative: 'Sciroppo d\'acero o zucchero da tavola (saccarosio)', nutrition: { kcal: 304, protein: 0.3, carbs: 82.4, fats: 0, fiber: 0.2, micronutrients: { sodium: 4, iron: 0.4, zinc: 0.2 } }, microDetails: { sodium: 4, iron: 0.4, zinc: 0.2 } },
  { id: '43', name: 'Sciroppo d\'Acero', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 260, protein: 0, carbs: 67, fats: 0.1, fiber: 0, micronutrients: { zinc: 2.8, sodium: 12, manganese: 2.9, calcium: 102, potassium: 212 } }, micros: ['zinc'], microDetails: { zinc: 2.8, sodium: 12, manganese: 2.9, calcium: 102, potassium: 212 } },
  { id: '44', name: 'Zenzero fresco', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 80, protein: 1.8, carbs: 17.8, fats: 0.8, fiber: 2, micronutrients: { potassium: 415, magnesium: 43, sodium: 13, phosphorus: 34, iron: 0.6, vitamin_c: 5, vitamin_b6: 0.2 } }, micros: ['potassium', 'magnesium'], microDetails: { potassium: 415, magnesium: 43, sodium: 13, phosphorus: 34, iron: 0.6, vitamin_c: 5, vitamin_b6: 0.2 } },
  { id: '59', name: 'Aceto di mele', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 22, protein: 0, carbs: 0.9, fats: 0, fiber: 0, micronutrients: { sodium: 5, potassium: 73, magnesium: 5, calcium: 7 } }, micros: ['potassium'], microDetails: { sodium: 5, potassium: 73, magnesium: 5, calcium: 7 } },
  { id: '60', name: 'Curcuma in polvere', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 312, protein: 9.7, carbs: 67, fats: 3.3, fiber: 22.7, micronutrients: { iron: 55, manganese: 19.8, potassium: 2080, vitamin_c: 1, zinc: 4.4 } }, micros: ['iron', 'manganese', 'potassium'], microDetails: { iron: 55, manganese: 19.8, potassium: 2080, vitamin_c: 1, zinc: 4.4 } },
  { id: '61', name: 'Senape (al naturale)', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 162, protein: 10, carbs: 13, fats: 10, fiber: 7, micronutrients: { selenium: 37, magnesium: 65, sodium: 1100, phosphorus: 180, manganese: 0.4 } }, micros: ['selenium', 'magnesium', 'sodium'], microDetails: { selenium: 37, magnesium: 65, sodium: 1100, phosphorus: 180, manganese: 0.4 } },
  { id: '62', name: 'Caffè espresso', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 9, protein: 0.1, carbs: 0, fats: 0.2, fiber: 0, micronutrients: { magnesium: 80, potassium: 115, sodium: 14, manganese: 0.5 } }, micros: ['magnesium', 'potassium'], microDetails: { magnesium: 80, potassium: 115, sodium: 14, manganese: 0.5 } },
  { id: '63', name: 'Tè verde (infuso)', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 1, protein: 0.2, carbs: 0.2, fats: 0, fiber: 0, micronutrients: { manganese: 0.2, potassium: 20, sodium: 1 } }, micros: ['manganese'], microDetails: { manganese: 0.2, potassium: 20, sodium: 1 } },
  { id: '64', name: 'Tisana camomilla (infuso)', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 1, protein: 0, carbs: 0.2, fats: 0, fiber: 0, micronutrients: { potassium: 9, sodium: 1, calcium: 2, magnesium: 1 } }, micros: ['potassium'], microDetails: { potassium: 9, sodium: 1, calcium: 2, magnesium: 1 } },
  { id: '65', name: 'Acqua minerale', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 0, protein: 0, carbs: 0, fats: 0, fiber: 0, micronutrients: { sodium: 2, calcium: 5, magnesium: 1, potassium: 0 } }, micros: ['sodium', 'calcium'], microDetails: { sodium: 2, calcium: 5, magnesium: 1, potassium: 0 } },
  { id: '66', name: 'Latte di avena senza zuccheri aggiunti', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 46, protein: 1, carbs: 8, fats: 1.5, fiber: 0.8, micronutrients: { calcium: 120, vitamin_d: 0.8, b12: 0.4, sodium: 40, phosphorus: 90 } }, micros: ['calcium', 'vitamin_d', 'b12'], microDetails: { calcium: 120, vitamin_d: 0.8, b12: 0.4, sodium: 40, phosphorus: 90 } },
  { id: '67', name: 'Burro chiarificato (Ghee)', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 876, protein: 0.3, carbs: 0, fats: 99.5, fiber: 0, micronutrients: { vitamin_a: 840, vitamin_e: 2.8, vitamin_k: 9, sodium: 2 } }, micros: ['vitamin_a', 'vitamin_e', 'vitamin_k'], microDetails: { vitamin_a: 840, vitamin_e: 2.8, vitamin_k: 9, sodium: 2 } },
  { id: '68', name: 'Noci (mix, max ~30g)', category: 'Condimenti/Altro', fodmapLevel: 'low', nutrition: { kcal: 654, protein: 15, carbs: 14, fats: 65, fiber: 6.7, micronutrients: { omega3: 9080, magnesium: 158, phosphorus: 346, copper: 1.6, manganese: 3.4, vitamin_b6: 0.5, folate: 98, zinc: 3.1 } }, micros: ['omega3', 'magnesium', 'phosphorus', 'copper', 'manganese'], microDetails: { omega3: 9080, magnesium: 158, phosphorus: 346, copper: 1.6, manganese: 3.4, vitamin_b6: 0.5, folate: 98, zinc: 3.1 } }
];
