import type { ExerciseAnim } from '../components/ExerciseFigure';

export type EquipmentType = 
  | 'bodyweight' 
  | 'dumbbells' 
  | 'bands' 
  | 'machine' 
  | 'barbell' 
  | 'kettlebell' 
  | 'pullup_bar' 
  | 'bench'
  | 'cardio_machine';

export type ExerciseCategory = 
  | 'cardio' 
  | 'strength_upper' 
  | 'strength_lower' 
  | 'strength_core' 
  | 'mobility' 
  | 'yoga' 
  | 'hiit' 
  | 'stretching'
  | 'rest';

export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';

export interface ExerciseInfo {
  id: string;
  name: string; // Chiave i18n: workout_{id}_name
  anim: ExerciseAnim;
  category: ExerciseCategory;
  equipment: EquipmentType[];
  /** MET value (Metabolic Equivalent of Task) - per calcolo calorie: MET * peso_kg * ore */
  met: number;
  /** Calorie al minuto per persona 70kg (stima basata su MET) */
  caloriesPerMinute: number;
  intensity: 'low' | 'moderate' | 'high' | 'very_high';
  difficulty: DifficultyLevel;
  targetMuscles: string[]; // Chiavi i18n: muscles.{muscle}
  secondaryMuscles?: string[];
  instructions: string; // Chiave i18n: workout_{id}_instructions
  steps: string[]; // Chiavi i18n: workout_{id}_step_1, workout_{id}_step_2, ...
  gifUrl?: string;
  fallbackImageUrl?: string;
  /** Durata consigliata in minuti per sessione standard */
  recommendedDurationMin: number;
  /** Serie x ripetizioni consigliate (per forza) o durata (per cardio/plank) */
  recommendedSetsReps: string;
  /** Note aggiuntive */
  notes?: string;
}

export interface WorkoutSuggestionProfile {
  moreCardio: boolean;
  moreStrength: boolean;
  lowImpact: boolean;
  reasonKey: string;
}

export interface WorkoutPlanInput {
  activityLevel: 'sedentary' | 'lightly_active' | 'moderately_active' | 'very_active' | 'extremely_active';
  goal: 'weight_loss' | 'muscle_gain' | 'maintenance' | 'health' | 'endurance';
  preferences: ('cardio' | 'strength' | 'yoga' | 'mixed')[];
  equipment: EquipmentType[];
  daysPerWeek: number; // 3-6
  sessionDurationMin: number; // 20-60
  intensity: 'low' | 'moderate' | 'high';
  focusAreas?: string[]; // es. ['core', 'glutes', 'upper_body']
}

export interface WeeklyWorkoutPlan {
  days: Record<string, DayWorkout>;
  totalSessionsPerWeek: number;
  estimatedWeeklyCaloriesBurned: number;
  notes: string;
}

export interface DayWorkout {
  day: string;
  exercises: PlannedExercise[];
  totalDurationMin: number;
  estimatedCaloriesBurned: number;
  focus: string;
}

export interface PlannedExercise {
  exerciseId: string;
  sets?: number;
  reps?: string; // es. "12-15" o "30 sec"
  durationMin?: number;
  restSec?: number;
  order: number;
  notes?: string;
}

// ============================================
// DATABASE ESERCIZI ESPANSO (50+ esercizi)
// ============================================

export const EXERCISES: Record<string, ExerciseInfo> = {
  // ========== CARDIO ==========
  walk: {
    id: 'walk',
    name: 'workout_walk_name',
    anim: 'walk',
    category: 'cardio',
    equipment: ['bodyweight'],
    met: 3.5,
    caloriesPerMinute: 4.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.legs', 'muscles.glutes', 'muscles.calves'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_walk_instructions',
    steps: [
      'workout_walk_step_1',
      'workout_walk_step_2',
      'workout_walk_step_3',
      'workout_walk_step_4',
    ],
    recommendedDurationMin: 30,
    recommendedSetsReps: '30-45 min',
    notes: 'Ideale per principianti e recupero attivo',
  },
  run: {
    id: 'run',
    name: 'workout_run_name',
    anim: 'walk',
    category: 'cardio',
    equipment: ['bodyweight'],
    met: 8.0,
    caloriesPerMinute: 10.5,
    intensity: 'high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.legs', 'muscles.glutes', 'muscles.calves', 'muscles.core'],
    secondaryMuscles: ['muscles.shoulders'],
    instructions: 'workout_run_instructions',
    steps: [
      'workout_run_step_1',
      'workout_run_step_2',
      'workout_run_step_3',
      'workout_run_step_4',
    ],
    recommendedDurationMin: 20,
    recommendedSetsReps: '20-30 min',
    notes: 'Inizia con intervalli corsa/camminata se principiante',
  },
  bike: {
    id: 'bike',
    name: 'workout_bike_name',
    anim: 'free',
    category: 'cardio',
    equipment: ['cardio_machine'],
    met: 7.0,
    caloriesPerMinute: 9.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.quads', 'muscles.glutes', 'muscles.calves'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.core'],
    instructions: 'workout_bike_instructions',
    steps: [
      'workout_bike_step_1',
      'workout_bike_step_2',
      'workout_bike_step_3',
    ],
    recommendedDurationMin: 30,
    recommendedSetsReps: '30-45 min',
    notes: 'Basso impatto sulle articolazioni',
  },
  swim: {
    id: 'swim',
    name: 'workout_swim_name',
    anim: 'swim',
    category: 'cardio',
    equipment: ['bodyweight'],
    met: 6.0,
    caloriesPerMinute: 8.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.full_body'],
    secondaryMuscles: ['muscles.shoulders', 'muscles.back', 'muscles.core'],
    instructions: 'workout_swim_instructions',
    steps: [
      'workout_swim_step_1',
      'workout_swim_step_2',
      'workout_swim_step_3',
    ],
    recommendedDurationMin: 30,
    recommendedSetsReps: '30-40 min',
    notes: 'Eccellente per chi ha problemi articolari',
  },
  jump_rope: {
    id: 'jump_rope',
    name: 'workout_jump_rope_name',
    anim: 'jump',
    category: 'cardio',
    equipment: ['bodyweight'],
    met: 10.0,
    caloriesPerMinute: 13.0,
    intensity: 'very_high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.calves', 'muscles.shoulders', 'muscles.core'],
    secondaryMuscles: ['muscles.quads', 'muscles.glutes'],
    instructions: 'workout_jump_rope_instructions',
    steps: [
      'workout_jump_rope_step_1',
      'workout_jump_rope_step_2',
      'workout_jump_rope_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '5 x 2 min',
    notes: 'Alto impatto - evitare se problemi ginocchia/caviglie',
  },

  // ========== FORZA - UPPER BODY ==========
  pushup: {
    id: 'pushup',
    name: 'workout_pushup_name',
    anim: 'pushup',
    category: 'strength_upper',
    equipment: ['bodyweight'],
    met: 3.8,
    caloriesPerMinute: 5.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.chest', 'muscles.triceps', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.core', 'muscles.serratus'],
    instructions: 'workout_pushup_instructions',
    steps: [
      'workout_pushup_step_1',
      'workout_pushup_step_2',
      'workout_pushup_step_3',
      'workout_pushup_step_4',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 10-15',
    notes: 'Modifica: ginocchia a terra se troppo difficile',
  },
  pushup_knee: {
    id: 'pushup_knee',
    name: 'workout_pushup_knee_name',
    anim: 'pushup',
    category: 'strength_upper',
    equipment: ['bodyweight'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.chest', 'muscles.triceps', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_pushup_knee_instructions',
    steps: [
      'workout_pushup_knee_step_1',
      'workout_pushup_knee_step_2',
      'workout_pushup_knee_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 12-20',
    notes: 'Versione facilitata per principianti',
  },
  pushup_incline: {
    id: 'pushup_incline',
    name: 'workout_pushup_incline_name',
    anim: 'pushup',
    category: 'strength_upper',
    equipment: ['bodyweight', 'bench'],
    met: 3.2,
    caloriesPerMinute: 4.2,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.upper_chest', 'muscles.triceps', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_pushup_incline_instructions',
    steps: [
      'workout_pushup_incline_step_1',
      'workout_pushup_incline_step_2',
      'workout_pushup_incline_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Focus su petto superiore - mani su superficie elevata',
  },
  pushup_decline: {
    id: 'pushup_decline',
    name: 'workout_pushup_decline_name',
    anim: 'pushup',
    category: 'strength_upper',
    equipment: ['bodyweight', 'bench'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'high',
    difficulty: 'advanced',
    targetMuscles: ['muscles.lower_chest', 'muscles.triceps', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_pushup_decline_instructions',
    steps: [
      'workout_pushup_decline_step_1',
      'workout_pushup_decline_step_2',
      'workout_pushup_decline_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 8-12',
    notes: 'Focus su petto inferiore - piedi elevati',
  },
  pullup: {
    id: 'pullup',
    name: 'workout_pullup_name',
    anim: 'row',
    category: 'strength_upper',
    equipment: ['pullup_bar'],
    met: 8.0,
    caloriesPerMinute: 10.5,
    intensity: 'high',
    difficulty: 'advanced',
    targetMuscles: ['muscles.lats', 'muscles.biceps', 'muscles.rear_delts'],
    secondaryMuscles: ['muscles.forearms', 'muscles.core'],
    instructions: 'workout_pullup_instructions',
    steps: [
      'workout_pullup_step_1',
      'workout_pullup_step_2',
      'workout_pullup_step_3',
      'workout_pullup_step_4',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 5-10',
    notes: 'Usa banda elastica per assistenza se necessario',
  },
  chinup: {
    id: 'chinup',
    name: 'workout_chinup_name',
    anim: 'row',
    category: 'strength_upper',
    equipment: ['pullup_bar'],
    met: 8.0,
    caloriesPerMinute: 10.5,
    intensity: 'high',
    difficulty: 'advanced',
    targetMuscles: ['muscles.biceps', 'muscles.lats', 'muscles.rear_delts'],
    secondaryMuscles: ['muscles.forearms', 'muscles.core'],
    instructions: 'workout_chinup_instructions',
    steps: [
      'workout_chinup_step_1',
      'workout_chinup_step_2',
      'workout_chinup_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 5-10',
    notes: 'Presa supina - più focus bicipiti',
  },
  dip: {
    id: 'dip',
    name: 'workout_dip_name',
    anim: 'press',
    category: 'strength_upper',
    equipment: ['bodyweight', 'bench'],
    met: 4.0,
    caloriesPerMinute: 5.5,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.triceps', 'muscles.chest', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_dip_instructions',
    steps: [
      'workout_dip_step_1',
      'workout_dip_step_2',
      'workout_dip_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 8-12',
    notes: 'Su panche parallele o bordo sedia/panchina',
  },
  bench_press: {
    id: 'bench_press',
    name: 'workout_bench_press_name',
    anim: 'press',
    category: 'strength_upper',
    equipment: ['barbell', 'bench'],
    met: 5.0,
    caloriesPerMinute: 6.5,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.chest', 'muscles.triceps', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.serratus', 'muscles.core'],
    instructions: 'workout_bench_press_instructions',
    steps: [
      'workout_bench_press_step_1',
      'workout_bench_press_step_2',
      'workout_bench_press_step_3',
      'workout_bench_press_step_4',
    ],
    recommendedDurationMin: 20,
    recommendedSetsReps: '3 x 8-12',
    notes: 'Esercizio base per forza petto',
  },
  dumbbell_bench_press: {
    id: 'dumbbell_bench_press',
    name: 'workout_dumbbell_bench_press_name',
    anim: 'press',
    category: 'strength_upper',
    equipment: ['dumbbells', 'bench'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.chest', 'muscles.triceps', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.serratus', 'muscles.core'],
    instructions: 'workout_dumbbell_bench_press_instructions',
    steps: [
      'workout_dumbbell_bench_press_step_1',
      'workout_dumbbell_bench_press_step_2',
      'workout_dumbbell_bench_press_step_3',
    ],
    recommendedDurationMin: 20,
    recommendedSetsReps: '3 x 10-12',
    notes: 'Maggior range of motion rispetto al bilanciere',
  },
  shoulder_press: {
    id: 'shoulder_press',
    name: 'workout_shoulder_press_name',
    anim: 'press',
    category: 'strength_upper',
    equipment: ['dumbbells', 'barbell'],
    met: 4.0,
    caloriesPerMinute: 5.5,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.shoulders', 'muscles.triceps'],
    secondaryMuscles: ['muscles.upper_chest', 'muscles.traps', 'muscles.core'],
    instructions: 'workout_shoulder_press_instructions',
    steps: [
      'workout_shoulder_press_step_1',
      'workout_shoulder_press_step_2',
      'workout_shoulder_press_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 10-12',
    notes: 'In piedi o seduto - core contratto',
  },
  lateral_raise: {
    id: 'lateral_raise',
    name: 'workout_lateral_raise_name',
    anim: 'free',
    category: 'strength_upper',
    equipment: ['dumbbells', 'bands'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.lateral_delts'],
    secondaryMuscles: ['muscles.front_delts', 'muscles.traps'],
    instructions: 'workout_lateral_raise_instructions',
    steps: [
      'workout_lateral_raise_step_1',
      'workout_lateral_raise_step_2',
      'workout_lateral_raise_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Peso leggero, movimento controllato',
  },
  row: {
    id: 'row',
    name: 'workout_row_name',
    anim: 'row',
    category: 'strength_upper',
    equipment: ['dumbbells', 'barbell', 'bands', 'machine'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.lats', 'muscles.rhomboids', 'muscles.rear_delts'],
    secondaryMuscles: ['muscles.biceps', 'muscles.forearms', 'muscles.core'],
    instructions: 'workout_row_instructions',
    steps: [
      'workout_row_step_1',
      'workout_row_step_2',
      'workout_row_step_3',
      'workout_row_step_4',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 10-12',
    notes: 'Tira verso l\'ombelico, scapole retratte',
  },
  biceps_curl: {
    id: 'biceps_curl',
    name: 'workout_biceps_curl_name',
    anim: 'curl',
    category: 'strength_upper',
    equipment: ['dumbbells', 'bands', 'barbell'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.biceps'],
    secondaryMuscles: ['muscles.forearms', 'muscles.front_delts'],
    instructions: 'workout_biceps_curl_instructions',
    steps: [
      'workout_biceps_curl_step_1',
      'workout_biceps_curl_step_2',
      'workout_biceps_curl_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Gomiti fissi ai lati, niente slancio',
  },
  triceps_extension: {
    id: 'triceps_extension',
    name: 'workout_triceps_extension_name',
    anim: 'press',
    category: 'strength_upper',
    equipment: ['dumbbells', 'bands', 'machine'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.triceps'],
    secondaryMuscles: [],
    instructions: 'workout_triceps_extension_instructions',
    steps: [
      'workout_triceps_extension_step_1',
      'workout_triceps_extension_step_2',
      'workout_triceps_extension_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Overhead o pushdown - gomiti vicini alla testa',
  },
  face_pull: {
    id: 'face_pull',
    name: 'workout_face_pull_name',
    anim: 'row',
    category: 'strength_upper',
    equipment: ['bands', 'machine'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.rear_delts', 'muscles.rhomboids', 'muscles.rotator_cuff'],
    secondaryMuscles: ['muscles.traps'],
    instructions: 'workout_face_pull_instructions',
    steps: [
      'workout_face_pull_step_1',
      'workout_face_pull_step_2',
      'workout_face_pull_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 15-20',
    notes: 'Fondamentale per salute spalla e postura',
  },

  // ========== FORZA - LOWER BODY ==========
  squat: {
    id: 'squat',
    name: 'workout_squat_name',
    anim: 'squat',
    category: 'strength_lower',
    equipment: ['bodyweight', 'dumbbells', 'barbell', 'kettlebell'],
    met: 5.0,
    caloriesPerMinute: 6.5,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.quads', 'muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.calves', 'muscles.core', 'muscles.lower_back'],
    instructions: 'workout_squat_instructions',
    steps: [
      'workout_squat_step_1',
      'workout_squat_step_2',
      'workout_squat_step_3',
      'workout_squat_step_4',
    ],
    recommendedDurationMin: 20,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Re del esercizi per gambe - scendi fino a parallelo',
  },
  goblet_squat: {
    id: 'goblet_squat',
    name: 'workout_goblet_squat_name',
    anim: 'squat',
    category: 'strength_lower',
    equipment: ['dumbbells', 'kettlebell'],
    met: 5.0,
    caloriesPerMinute: 6.5,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.quads', 'muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.core', 'muscles.upper_back'],
    instructions: 'workout_goblet_squat_instructions',
    steps: [
      'workout_goblet_squat_step_1',
      'workout_goblet_squat_step_2',
      'workout_goblet_squat_step_3',
    ],
    recommendedDurationMin: 20,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Peso al petto - insegna pattern corretto',
  },
  lunge: {
    id: 'lunge',
    name: 'workout_lunge_name',
    anim: 'lunge',
    category: 'strength_lower',
    equipment: ['bodyweight', 'dumbbells', 'barbell'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.quads', 'muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.calves', 'muscles.core'],
    instructions: 'workout_lunge_instructions',
    steps: [
      'workout_lunge_step_1',
      'workout_lunge_step_2',
      'workout_lunge_step_3',
      'workout_lunge_step_4',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 10-12 per gamba',
    notes: 'Ginocchio non oltre la punta del piede',
  },
  reverse_lunge: {
    id: 'reverse_lunge',
    name: 'workout_reverse_lunge_name',
    anim: 'lunge',
    category: 'strength_lower',
    equipment: ['bodyweight', 'dumbbells'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.glutes', 'muscles.quads'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.core'],
    instructions: 'workout_reverse_lunge_instructions',
    steps: [
      'workout_reverse_lunge_step_1',
      'workout_reverse_lunge_step_2',
      'workout_reverse_lunge_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 10-12 per gamba',
    notes: 'Meno stress su ginocchia rispetto affondi frontali',
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'workout_bulgarian_split_squat_name',
    anim: 'lunge',
    category: 'strength_lower',
    equipment: ['bodyweight', 'dumbbells', 'bench'],
    met: 5.5,
    caloriesPerMinute: 7.0,
    intensity: 'high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.quads', 'muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.calves', 'muscles.core'],
    instructions: 'workout_bulgarian_split_squat_instructions',
    steps: [
      'workout_bulgarian_split_squat_step_1',
      'workout_bulgarian_split_squat_step_2',
      'workout_bulgarian_split_squat_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 8-10 per gamba',
    notes: 'Piede posteriore su panca - molto intenso',
  },
  deadlift: {
    id: 'deadlift',
    name: 'workout_deadlift_name',
    anim: 'free',
    category: 'strength_lower',
    equipment: ['barbell', 'dumbbells', 'kettlebell'],
    met: 6.0,
    caloriesPerMinute: 8.0,
    intensity: 'high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.hamstrings', 'muscles.glutes', 'muscles.lower_back'],
    secondaryMuscles: ['muscles.traps', 'muscles.forearms', 'muscles.core', 'muscles.lats'],
    instructions: 'workout_deadlift_instructions',
    steps: [
      'workout_deadlift_step_1',
      'workout_deadlift_step_2',
      'workout_deadlift_step_3',
      'workout_deadlift_step_4',
    ],
    recommendedDurationMin: 20,
    recommendedSetsReps: '3 x 8-10',
    notes: 'Schiena neutra, spingi con i talloni',
  },
  romanian_deadlift: {
    id: 'romanian_deadlift',
    name: 'workout_romanian_deadlift_name',
    anim: 'free',
    category: 'strength_lower',
    equipment: ['barbell', 'dumbbells'],
    met: 5.0,
    caloriesPerMinute: 6.5,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.hamstrings', 'muscles.glutes'],
    secondaryMuscles: ['muscles.lower_back', 'muscles.core'],
    instructions: 'workout_romanian_deadlift_instructions',
    steps: [
      'workout_romanian_deadlift_step_1',
      'workout_romanian_deadlift_step_2',
      'workout_romanian_deadlift_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 10-12',
    notes: 'Focus catena posteriore - ginocchia leggermente flesse',
  },
  hip_thrust: {
    id: 'hip_thrust',
    name: 'workout_hip_thrust_name',
    anim: 'free',
    category: 'strength_lower',
    equipment: ['barbell', 'dumbbells', 'bench', 'bands'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.core', 'muscles.lower_back'],
    instructions: 'workout_hip_thrust_instructions',
    steps: [
      'workout_hip_thrust_step_1',
      'workout_hip_thrust_step_2',
      'workout_hip_thrust_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Miglior esercizio per glutei - spingi talloni',
  },
  glute_bridge: {
    id: 'glute_bridge',
    name: 'workout_glute_bridge_name',
    anim: 'free',
    category: 'strength_lower',
    equipment: ['bodyweight', 'bands', 'dumbbells'],
    met: 3.5,
    caloriesPerMinute: 4.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.core'],
    instructions: 'workout_glute_bridge_instructions',
    steps: [
      'workout_glute_bridge_step_1',
      'workout_glute_bridge_step_2',
      'workout_glute_bridge_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 15-20',
    notes: 'Versione base hip thrust - a terra',
  },
  calf_raise: {
    id: 'calf_raise',
    name: 'workout_calf_raise_name',
    anim: 'calf',
    category: 'strength_lower',
    equipment: ['bodyweight', 'dumbbells', 'machine'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.calves'],
    secondaryMuscles: [],
    instructions: 'workout_calf_raise_instructions',
    steps: [
      'workout_calf_raise_step_1',
      'workout_calf_raise_step_2',
      'workout_calf_raise_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 15-20',
    notes: 'Punta piedi dritta, in dentro, in fuori per completo sviluppo',
  },
  leg_press: {
    id: 'leg_press',
    name: 'workout_leg_press_name',
    anim: 'squat',
    category: 'strength_lower',
    equipment: ['machine'],
    met: 4.5,
    caloriesPerMinute: 6.0,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.quads', 'muscles.glutes'],
    secondaryMuscles: ['muscles.hamstrings', 'muscles.calves'],
    instructions: 'workout_leg_press_instructions',
    steps: [
      'workout_leg_press_step_1',
      'workout_leg_press_step_2',
      'workout_leg_press_step_3',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: '3 x 12-15',
    notes: 'Macchina - sicuro per carichi alti',
  },

  // ========== CORE ==========
  plank: {
    id: 'plank',
    name: 'workout_plank_name',
    anim: 'plank',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.core', 'muscles.abs'],
    secondaryMuscles: ['muscles.shoulders', 'muscles.glutes', 'muscles.quads'],
    instructions: 'workout_plank_instructions',
    steps: [
      'workout_plank_step_1',
      'workout_plank_step_2',
      'workout_plank_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 30-60 sec',
    notes: 'Corpo in linea retta, ombelico verso colonna',
  },
  side_plank: {
    id: 'side_plank',
    name: 'workout_side_plank_name',
    anim: 'plank',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.obliques', 'muscles.core'],
    secondaryMuscles: ['muscles.shoulders', 'muscles.glute_med'],
    instructions: 'workout_side_plank_instructions',
    steps: [
      'workout_side_plank_step_1',
      'workout_side_plank_step_2',
      'workout_side_plank_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 20-40 sec per lato',
    notes: 'Fianchi alti, non ruotare in avanti',
  },
  crunch: {
    id: 'crunch',
    name: 'workout_crunch_name',
    anim: 'free',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 2.5,
    caloriesPerMinute: 3.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.abs'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_crunch_instructions',
    steps: [
      'workout_crunch_step_1',
      'workout_crunch_step_2',
      'workout_crunch_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 15-20',
    notes: 'Sollevare solo scapole, non tirare collo',
  },
  russian_twist: {
    id: 'russian_twist',
    name: 'workout_russian_twist_name',
    anim: 'twist',
    category: 'strength_core',
    equipment: ['bodyweight', 'dumbbells', 'kettlebell'],
    met: 3.5,
    caloriesPerMinute: 4.5,
    intensity: 'moderate',
    difficulty: 'beginner',
    targetMuscles: ['muscles.obliques', 'muscles.abs'],
    secondaryMuscles: ['muscles.hip_flexors'],
    instructions: 'workout_russian_twist_instructions',
    steps: [
      'workout_russian_twist_step_1',
      'workout_russian_twist_step_2',
      'workout_russian_twist_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 20 totali',
    notes: 'Piedi a terra se principiante, sollevati se avanzato',
  },
  leg_raise: {
    id: 'leg_raise',
    name: 'workout_leg_raise_name',
    anim: 'free',
    category: 'strength_core',
    equipment: ['bodyweight', 'pullup_bar'],
    met: 3.5,
    caloriesPerMinute: 4.5,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.lower_abs', 'muscles.hip_flexors'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_leg_raise_instructions',
    steps: [
      'workout_leg_raise_step_1',
      'workout_leg_raise_step_2',
      'workout_leg_raise_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 10-15',
    notes: 'Schiena premuta a terra, non inarcare lombari',
  },
  mountain_climber: {
    id: 'mountain_climber',
    name: 'workout_mountain_climber_name',
    anim: 'jump',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 8.0,
    caloriesPerMinute: 10.5,
    intensity: 'high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.core', 'muscles.abs', 'muscles.shoulders'],
    secondaryMuscles: ['muscles.quads', 'muscles.hip_flexors', 'muscles.glutes'],
    instructions: 'workout_mountain_climber_instructions',
    steps: [
      'workout_mountain_climber_step_1',
      'workout_mountain_climber_step_2',
      'workout_mountain_climber_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 30-45 sec',
    notes: 'Anche cardio - mantieni bacino stabile',
  },
  bird_dog: {
    id: 'bird_dog',
    name: 'workout_bird_dog_name',
    anim: 'free',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 2.5,
    caloriesPerMinute: 3.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.core', 'muscles.lower_back', 'muscles.glutes'],
    secondaryMuscles: ['muscles.shoulders'],
    instructions: 'workout_bird_dog_instructions',
    steps: [
      'workout_bird_dog_step_1',
      'workout_bird_dog_step_2',
      'workout_bird_dog_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 10 per lato',
    notes: 'Stabilità colonna - opposto braccio/gamba',
  },
  dead_bug: {
    id: 'dead_bug',
    name: 'workout_dead_bug_name',
    anim: 'free',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 2.5,
    caloriesPerMinute: 3.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.core', 'muscles.abs'],
    secondaryMuscles: ['muscles.hip_flexors'],
    instructions: 'workout_dead_bug_instructions',
    steps: [
      'workout_dead_bug_step_1',
      'workout_dead_bug_step_2',
      'workout_dead_bug_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 10 per lato',
    notes: 'Lombari incollati a terra - anti-estensione',
  },
  hollow_body: {
    id: 'hollow_body',
    name: 'workout_hollow_body_name',
    anim: 'free',
    category: 'strength_core',
    equipment: ['bodyweight'],
    met: 3.5,
    caloriesPerMinute: 4.5,
    intensity: 'moderate',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.abs', 'muscles.core', 'muscles.hip_flexors'],
    secondaryMuscles: [],
    instructions: 'workout_hollow_body_instructions',
    steps: [
      'workout_hollow_body_step_1',
      'workout_hollow_body_step_2',
      'workout_hollow_body_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 20-30 sec',
    notes: 'Posizione ginnastica - lombari a terra',
  },

  // ========== MOBILITÀ / YOGA ==========
  yoga: {
    id: 'yoga',
    name: 'workout_yoga_name',
    anim: 'twist',
    category: 'yoga',
    equipment: ['bodyweight'],
    met: 2.5,
    caloriesPerMinute: 3.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.full_body'],
    secondaryMuscles: [],
    instructions: 'workout_yoga_instructions',
    steps: [
      'workout_yoga_step_1',
      'workout_yoga_step_2',
      'workout_yoga_step_3',
    ],
    recommendedDurationMin: 30,
    recommendedSetsReps: '20-40 min flow',
    notes: 'Focus respiro e consapevolezza corporea',
  },
  cat_cow: {
    id: 'cat_cow',
    name: 'workout_cat_cow_name',
    anim: 'twist',
    category: 'mobility',
    equipment: ['bodyweight'],
    met: 2.0,
    caloriesPerMinute: 2.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.spine', 'muscles.core'],
    secondaryMuscles: [],
    instructions: 'workout_cat_cow_instructions',
    steps: [
      'workout_cat_cow_step_1',
      'workout_cat_cow_step_2',
      'workout_cat_cow_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '10-15 cicli',
    notes: 'Mobilizzazione colonna - sincronizza con respiro',
  },
  child_pose: {
    id: 'child_pose',
    name: 'workout_child_pose_name',
    anim: 'rest',
    category: 'yoga',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.lower_back', 'muscles.hips', 'muscles.shoulders'],
    secondaryMuscles: [],
    instructions: 'workout_child_pose_instructions',
    steps: [
      'workout_child_pose_step_1',
      'workout_child_pose_step_2',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-60 sec',
    notes: 'Posizione di riposo e allungamento',
  },
  downward_dog: {
    id: 'downward_dog',
    name: 'workout_downward_dog_name',
    anim: 'free',
    category: 'yoga',
    equipment: ['bodyweight'],
    met: 2.5,
    caloriesPerMinute: 3.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.hamstrings', 'muscles.calves', 'muscles.shoulders', 'muscles.spine'],
    secondaryMuscles: ['muscles.core'],
    instructions: 'workout_downward_dog_instructions',
    steps: [
      'workout_downward_dog_step_1',
      'workout_downward_dog_step_2',
      'workout_downward_dog_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-60 sec',
    notes: 'Pedala i talloni per allungare polpacci',
  },
  cobra: {
    id: 'cobra',
    name: 'workout_cobra_name',
    anim: 'free',
    category: 'yoga',
    equipment: ['bodyweight'],
    met: 2.0,
    caloriesPerMinute: 2.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.abs', 'muscles.chest', 'muscles.spine'],
    secondaryMuscles: ['muscles.shoulders'],
    instructions: 'workout_cobra_instructions',
    steps: [
      'workout_cobra_step_1',
      'workout_cobra_step_2',
      'workout_cobra_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '3 x 15-30 sec',
    notes: 'Estensione colonna - non forzare lombari',
  },
  pigeon_pose: {
    id: 'pigeon_pose',
    name: 'workout_pigeon_pose_name',
    anim: 'free',
    category: 'yoga',
    equipment: ['bodyweight'],
    met: 2.0,
    caloriesPerMinute: 2.5,
    intensity: 'low',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.glutes', 'muscles.hip_flexors', 'muscles.piriformis'],
    secondaryMuscles: ['muscles.lower_back'],
    instructions: 'workout_pigeon_pose_instructions',
    steps: [
      'workout_pigeon_pose_step_1',
      'workout_pigeon_pose_step_2',
      'workout_pigeon_pose_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-60 sec per lato',
    notes: 'Profondo allungamento anca - usa supporto se serve',
  },
  hip_flexor_stretch: {
    id: 'hip_flexor_stretch',
    name: 'workout_hip_flexor_stretch_name',
    anim: 'lunge',
    category: 'mobility',
    equipment: ['bodyweight'],
    met: 2.0,
    caloriesPerMinute: 2.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.hip_flexors', 'muscles.quads'],
    secondaryMuscles: ['muscles.abs'],
    instructions: 'workout_hip_flexor_stretch_instructions',
    steps: [
      'workout_hip_flexor_stretch_step_1',
      'workout_hip_flexor_stretch_step_2',
      'workout_hip_flexor_stretch_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-45 sec per lato',
    notes: 'Attiva gluteo gamba posteriore per maggior allungamento',
  },
  thoracic_rotation: {
    id: 'thoracic_rotation',
    name: 'workout_thoracic_rotation_name',
    anim: 'twist',
    category: 'mobility',
    equipment: ['bodyweight'],
    met: 2.0,
    caloriesPerMinute: 2.5,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.thoracic_spine', 'muscles.chest', 'muscles.shoulders'],
    secondaryMuscles: [],
    instructions: 'workout_thoracic_rotation_instructions',
    steps: [
      'workout_thoracic_rotation_step_1',
      'workout_thoracic_rotation_step_2',
      'workout_thoracic_rotation_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '10-12 per lato',
    notes: 'Mobilità toracica - cruciale per postura',
  },

  // ========== HIIT ==========
  burpees: {
    id: 'burpees',
    name: 'workout_burpees_name',
    anim: 'jump',
    category: 'hiit',
    equipment: ['bodyweight'],
    met: 10.0,
    caloriesPerMinute: 13.0,
    intensity: 'very_high',
    difficulty: 'advanced',
    targetMuscles: ['muscles.full_body'],
    secondaryMuscles: ['muscles.chest', 'muscles.legs', 'muscles.core', 'muscles.shoulders'],
    instructions: 'workout_burpees_instructions',
    steps: [
      'workout_burpees_step_1',
      'workout_burpees_step_2',
      'workout_burpees_step_3',
      'workout_burpees_step_4',
      'workout_burpees_step_5',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '4 x 30 sec / 30 sec riposo',
    notes: 'Esercizio completo ad alta intensità - modifica: no salto',
  },
  jumping_jacks: {
    id: 'jumping_jacks',
    name: 'workout_jumping_jacks_name',
    anim: 'jump',
    category: 'hiit',
    equipment: ['bodyweight'],
    met: 8.0,
    caloriesPerMinute: 10.5,
    intensity: 'high',
    difficulty: 'beginner',
    targetMuscles: ['muscles.full_body'],
    secondaryMuscles: ['muscles.shoulders', 'muscles.quads', 'muscles.glutes'],
    instructions: 'workout_jumping_jacks_instructions',
    steps: [
      'workout_jumping_jacks_step_1',
      'workout_jumping_jacks_step_2',
      'workout_jumping_jacks_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 45 sec',
    notes: 'Riscaldamento o cardio HIIT',
  },
  high_knees: {
    id: 'high_knees',
    name: 'workout_high_knees_name',
    anim: 'jump',
    category: 'hiit',
    equipment: ['bodyweight'],
    met: 8.5,
    caloriesPerMinute: 11.0,
    intensity: 'high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.quads', 'muscles.hip_flexors', 'muscles.core'],
    secondaryMuscles: ['muscles.calves', 'muscles.shoulders'],
    instructions: 'workout_high_knees_instructions',
    steps: [
      'workout_high_knees_step_1',
      'workout_high_knees_step_2',
      'workout_high_knees_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 30-45 sec',
    notes: 'Ginocchia al petto - braccia opposte',
  },
  butt_kickers: {
    id: 'butt_kickers',
    name: 'workout_butt_kickers_name',
    anim: 'jump',
    category: 'hiit',
    equipment: ['bodyweight'],
    met: 7.0,
    caloriesPerMinute: 9.0,
    intensity: 'high',
    difficulty: 'beginner',
    targetMuscles: ['muscles.hamstrings', 'muscles.glutes', 'muscles.quads'],
    secondaryMuscles: ['muscles.calves', 'muscles.core'],
    instructions: 'workout_butt_kickers_instructions',
    steps: [
      'workout_butt_kickers_step_1',
      'workout_butt_kickers_step_2',
      'workout_butt_kickers_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 45 sec',
    notes: 'Talloni ai glutei - corsa sul posto',
  },
  squat_jump: {
    id: 'squat_jump',
    name: 'workout_squat_jump_name',
    anim: 'jump',
    category: 'hiit',
    equipment: ['bodyweight'],
    met: 9.0,
    caloriesPerMinute: 12.0,
    intensity: 'very_high',
    difficulty: 'intermediate',
    targetMuscles: ['muscles.quads', 'muscles.glutes', 'muscles.calves'],
    secondaryMuscles: ['muscles.core', 'muscles.hamstrings'],
    instructions: 'workout_squat_jump_instructions',
    steps: [
      'workout_squat_jump_step_1',
      'workout_squat_jump_step_2',
      'workout_squat_jump_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '3 x 10-15',
    notes: 'Atterra morbido - assorbi con ginocchia',
  },

  // ========== STRETCHING ==========
  hamstring_stretch: {
    id: 'hamstring_stretch',
    name: 'workout_hamstring_stretch_name',
    anim: 'free',
    category: 'stretching',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.hamstrings'],
    secondaryMuscles: ['muscles.calves', 'muscles.lower_back'],
    instructions: 'workout_hamstring_stretch_instructions',
    steps: [
      'workout_hamstring_stretch_step_1',
      'workout_hamstring_stretch_step_2',
      'workout_hamstring_stretch_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-45 sec per gamba',
    notes: 'Schiena dritta - piega da anche non da vita',
  },
  quad_stretch: {
    id: 'quad_stretch',
    name: 'workout_quad_stretch_name',
    anim: 'free',
    category: 'stretching',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.quads', 'muscles.hip_flexors'],
    secondaryMuscles: [],
    instructions: 'workout_quad_stretch_instructions',
    steps: [
      'workout_quad_stretch_step_1',
      'workout_quad_stretch_step_2',
      'workout_quad_stretch_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-45 sec per gamba',
    notes: 'In piedi o sdraiato - bacino in retroversione',
  },
  chest_stretch: {
    id: 'chest_stretch',
    name: 'workout_chest_stretch_name',
    anim: 'free',
    category: 'stretching',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.chest', 'muscles.front_delts', 'muscles.biceps'],
    secondaryMuscles: [],
    instructions: 'workout_chest_stretch_instructions',
    steps: [
      'workout_chest_stretch_step_1',
      'workout_chest_stretch_step_2',
      'workout_chest_stretch_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-45 sec',
    notes: 'A parete o porta - braccio a 90°',
  },
  shoulder_stretch: {
    id: 'shoulder_stretch',
    name: 'workout_shoulder_stretch_name',
    anim: 'free',
    category: 'stretching',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.shoulders', 'muscles.lats', 'muscles.triceps'],
    secondaryMuscles: [],
    instructions: 'workout_shoulder_stretch_instructions',
    steps: [
      'workout_shoulder_stretch_step_1',
      'workout_shoulder_stretch_step_2',
      'workout_shoulder_stretch_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-45 sec per lato',
    notes: 'Braccio attraverso petto o sopra testa',
  },
  triceps_stretch: {
    id: 'triceps_stretch',
    name: 'workout_triceps_stretch_name',
    anim: 'free',
    category: 'stretching',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.triceps', 'muscles.lats', 'muscles.shoulders'],
    secondaryMuscles: [],
    instructions: 'workout_triceps_stretch_instructions',
    steps: [
      'workout_triceps_stretch_step_1',
      'workout_triceps_stretch_step_2',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30 sec per lato',
    notes: 'Gomito verso alto, mano dietro collo',
  },
  lower_back_stretch: {
    id: 'lower_back_stretch',
    name: 'workout_lower_back_stretch_name',
    anim: 'free',
    category: 'stretching',
    equipment: ['bodyweight'],
    met: 1.5,
    caloriesPerMinute: 2.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.lower_back', 'muscles.glutes', 'muscles.hamstrings'],
    secondaryMuscles: [],
    instructions: 'workout_lower_back_stretch_instructions',
    steps: [
      'workout_lower_back_stretch_step_1',
      'workout_lower_back_stretch_step_2',
      'workout_lower_back_stretch_step_3',
    ],
    recommendedDurationMin: 5,
    recommendedSetsReps: '30-60 sec',
    notes: 'Ginocchia al petto o posizione del bambino',
  },

  // ========== REST ==========
  rest: {
    id: 'rest',
    name: 'workout_rest_name',
    anim: 'rest',
    category: 'rest',
    equipment: ['bodyweight'],
    met: 1.0,
    caloriesPerMinute: 1.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: [],
    secondaryMuscles: [],
    instructions: 'workout_rest_instructions',
    steps: [
      'workout_rest_step_1',
    ],
    recommendedDurationMin: 15,
    recommendedSetsReps: 'Giorno intero',
    notes: 'Recupero completo - camminata leggera opzionale',
  },
  breathe: {
    id: 'breathe',
    name: 'workout_breathe_name',
    anim: 'breathe',
    category: 'rest',
    equipment: ['bodyweight'],
    met: 1.0,
    caloriesPerMinute: 1.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.diaphragm'],
    secondaryMuscles: [],
    instructions: 'workout_breathe_instructions',
    steps: [
      'workout_breathe_step_1',
      'workout_breathe_step_2',
      'workout_breathe_step_3',
    ],
    recommendedDurationMin: 10,
    recommendedSetsReps: '5-10 min',
    notes: 'Respirazione diaframmatica - riduce stress',
  },
  free: {
    id: 'free',
    name: 'workout_free_name',
    anim: 'free',
    category: 'rest',
    equipment: ['bodyweight'],
    met: 3.0,
    caloriesPerMinute: 4.0,
    intensity: 'low',
    difficulty: 'beginner',
    targetMuscles: ['muscles.full_body'],
    secondaryMuscles: [],
    instructions: 'workout_free_instructions',
    steps: [
      'workout_free_step_1',
    ],
    recommendedDurationMin: 30,
    recommendedSetsReps: 'Libero',
    notes: 'Attività a scelta: sport, passeggiata, gioco',
  },
};

// Ordine per selettore (categorie raggruppate)
export const EXERCISE_ORDER: string[] = [
  // Cardio
  'walk', 'run', 'bike', 'swim', 'jump_rope',
  // Strength Upper
  'pushup', 'pushup_knee', 'pushup_incline', 'pushup_decline',
  'pullup', 'chinup', 'dip',
  'bench_press', 'dumbbell_bench_press',
  'shoulder_press', 'lateral_raise', 'face_pull',
  'row', 'biceps_curl', 'triceps_extension',
  // Strength Lower
  'squat', 'goblet_squat', 'lunge', 'reverse_lunge', 'bulgarian_split_squat',
  'deadlift', 'romanian_deadlift', 'hip_thrust', 'glute_bridge', 'calf_raise', 'leg_press',
  // Core
  'plank', 'side_plank', 'crunch', 'russian_twist', 'leg_raise', 'mountain_climber', 'bird_dog', 'dead_bug', 'hollow_body',
  // Mobility/Yoga
  'yoga', 'cat_cow', 'child_pose', 'downward_dog', 'cobra', 'pigeon_pose', 'hip_flexor_stretch', 'thoracic_rotation',
  // HIIT
  'burpees', 'jumping_jacks', 'high_knees', 'butt_kickers', 'squat_jump',
  // Stretching
  'hamstring_stretch', 'quad_stretch', 'chest_stretch', 'shoulder_stretch', 'triceps_stretch', 'lower_back_stretch',
  // Rest
  'rest', 'breathe', 'free',
];

// Helper functions
export function getExercisesByCategory(category: ExerciseCategory): ExerciseInfo[] {
  return Object.values(EXERCISES).filter(ex => ex.category === category);
}

export function getExercisesByEquipment(equipment: EquipmentType): ExerciseInfo[] {
  return Object.values(EXERCISES).filter(ex => ex.equipment.includes(equipment));
}

export function getExercisesByDifficulty(difficulty: DifficultyLevel): ExerciseInfo[] {
  return Object.values(EXERCISES).filter(ex => ex.difficulty === difficulty);
}

export function getExercisesByIntensity(intensity: ExerciseInfo['intensity']): ExerciseInfo[] {
  return Object.values(EXERCISES).filter(ex => ex.intensity === intensity);
}

export function getExercisesByTargetMuscle(muscle: string): ExerciseInfo[] {
  return Object.values(EXERCISES).filter(ex => 
    ex.targetMuscles.includes(muscle) || ex.secondaryMuscles?.includes(muscle)
  );
}

export function calculateExerciseCalories(exerciseId: string, weightKg: number, durationMin: number): number {
  const exercise = EXERCISES[exerciseId];
  if (!exercise) return 0;
  // MET * peso_kg * (durata_min / 60)
  return Math.round(exercise.met * weightKg * (durationMin / 60));
}

export function calculateWorkoutCalories(exercises: PlannedExercise[], weightKg: number): number {
  return exercises.reduce((total, ex) => {
    const exercise = EXERCISES[ex.exerciseId];
    if (!exercise) return total;
    const duration = ex.durationMin || exercise.recommendedDurationMin;
    return total + calculateExerciseCalories(ex.exerciseId, weightKg, duration);
  }, 0);
}
